### ISSUE TITLE
Add a good documentation for this repository

### ISSUE THREAD

**Issue by varunvjha** [varunvjha/DataStructureImplementations#8]
Make a good and responsive document for this repository

**Comment by ayushi-1408** [comment]
Hey! please assign me this issue.

**Comment by varunvjha** [comment]
Sure, go ahead.

**Comment by ayushi-1408** [comment]
Hey! I have added a code of conduct and done some changes . Hope you will like it and merge it.

**Comment by ayushi-1408** [comment]
Hey! @varunvjha  Can you please put the label Hactoberfest-accepted so that it can count as my valid PR.
